### ISSUE TITLE
meta-rauc-sunxi: does not support current yocto releases

### ISSUE THREAD

**Issue by jluebbe** [rauc/meta-rauc-community#115]
`meta-rauc-sunxi/conf/layer.conf` in master has `LAYERSERIES_COMPAT_meta-rauc-sunxi = "dunfell gatesgarth hardknott honister"`, so it wouldn't work with the [current releases](https://wiki.yoctoproject.org/wiki/Releases) (kirkstone, scarthgap and styhead).

This layer was originally contributed by @MitchGaines in #17 and #18. @dev-0x7C6 updated it to the new override syntax. Would either of you be interested in updating it to e.g. scarthgap and/or styhead? Otherwise, we should probably think about removing it until there is more interest again.

**Comment by MitchGaines** [comment]
I am no longer supporting this. However, it seems kind of silly to remove it just because it's out of date so long as the supported versions are clearly communicated. Someone will come along wanting this and this provides a good starting point.

**Comment by jluebbe** [comment]
We could remove it in master (which is supposed to correspond to the most current yocto release), keep it in an older branch (e.g. https://github.com/rauc/meta-rauc-community/tree/dunfell) and then point to it from the readme.

In case someone wants to pick up maintenance again, the removal commit would be easy to revert.

**Comment by leon-anavi** [comment]
> In case someone wants to pick up maintenance again, the removal commit would be easy to revert.

Let's keep it for the moment. I have old Olimex and Orange Pi boards with Allwinner. I will have a look at it when I have spare cycles.

Best regards,
Leon

**Comment by leon-anavi** [comment]
I got meta-rauc-sunxi working on Olimex A10-OLinuXino-LIME for Yocto release Scarthgap. The GitHub pull request is available at #117

@MitchGaines if you have any spare time, could you please have a quick look at it as you have original contributed this layer? 

Best regards,
Leon

**Comment by leon-anavi** [comment]
This is the GitHub pull request for meta-rauc-sunxi and Yocto release Styhead: https://github.com/rauc/meta-rauc-community/pull/118 It has been based on GitHub pull request #117 for Scarthgap. The most notable difference is the `WORKDIR` -> `UNPACKDIR` transition. I have tested it on [Olimex A10-OLinuXino-LIME](https://www.olimex.com/Products/OLinuXino/A10/A10-OLinuXino-LIME-n4GB/open-source-hardware).

**Comment by leon-anavi** [comment]
I merged the patches in master (Styhead) and Scarthgap. Sub-layer meta-rauc-sunxi is a good state right now with 4 supported boards on which I have tested. Considering the road map of Scarthgap as a Long Term Support release, we will have sunxi support for RAUC until at least April 2028 :)
