### ISSUE TITLE
meta-rauc-tegra: does not support current yocto releases

### ISSUE THREAD

**Issue by jluebbe** [rauc/meta-rauc-community#116]
`meta-rauc-tegra/conf/layer.conf` in master has `meta-rauc-tegra/conf/layer.conf:13:LAYERSERIES_COMPAT_meta-rauc-tegra = "honister"`, so it wouldn't work with the [current releases](https://wiki.yoctoproject.org/wiki/Releases) (kirkstone, scarthgap and styhead).

This layer was originally contributed by @leon-anavi  in #27. @stlachev updated the compatibility to `kirkstone` in that branch, but not in master (#58). Would either of you be interested in updating it to e.g. scarthgap and/or styhead in master? Otherwise, we could think about removing it until there is more interest again.

**Comment by leon-anavi** [comment]
Unfortunately, meta-tegra has dropped support for Jetson TX2. We don't support any other NVIDIA Tegra devices therefore I dropped meta-rauc-tegra from the master branch of meta-rauc-community: https://github.com/rauc/meta-rauc-community/pull/119
