### ISSUE TITLE
Building on scarthgap: dependency missing

### ISSUE THREAD

**Issue by hmdevelopers** [rauc/meta-rauc-community#124]
Build on scarthgap fails because dependency on layer/recipe atf-sunxi is missing.

**Comment by hmdevelopers** [comment]
Could fix by substituting atf-sunxi with trusted-firmware-a:

From 48a3649b7073c8e23ec63648eff1bcd596534e7a Mon Sep 17 00:00:00 2001
From: Andrea Moretto <developers@hypermatrix.com>
Date: Tue, 22 Oct 2024 14:28:24 +0200
Subject: [PATCH] Substituted legacy atf-sunxi with trusted-firmware-a

---
 meta-rauc-sunxi/recipes-bsp/u-boot/u-boot_%.bbappend | 4 ++--
 1 file changed, 2 insertions(+), 2 deletions(-)

diff --git a/meta-rauc-sunxi/recipes-bsp/u-boot/u-boot_%.bbappend b/meta-rauc-sunxi/recipes-bsp/u-boot/u-boot_%.bbappend
index 3c423cc..dd6567e 100644
--- a/meta-rauc-sunxi/recipes-bsp/u-boot/u-boot_%.bbappend
+++ b/meta-rauc-sunxi/recipes-bsp/u-boot/u-boot_%.bbappend
@@ -1,7 +1,7 @@
 FILESEXTRAPATHS:prepend := "${THISDIR}/files:"
 
 DEPENDS += " bc-native dtc-native swig-native python3-native flex-native bison-native "
-DEPENDS:append:sun50i = " atf-sunxi "
+DEPENDS:append:sun50i = " trusted-firmware-a "
 
 COMPATIBLE_MACHINE = "(sun4i|sun5i|sun7i|sun8i|sun50i)"
 
@@ -26,7 +26,7 @@ UBOOT_ENV = "boot"
 EXTRA_OEMAKE += ' HOSTLDSHARED="${BUILD_CC} -shared ${BUILD_LDFLAGS} ${BUILD_CFLAGS}" '
 EXTRA_OEMAKE:append:sun50i = " BL31=${DEPLOY_DIR_IMAGE}/bl31.bin "
 
-do_compile_sun50i[depends] += "atf-sunxi:do_deploy"
+do_compile_sun50i[depends] += "trusted-firmware-a:do_deploy"
 
 do_compile:append() {
     ${B}/tools/mkimage -C none -A arm -T script -d ${WORKDIR}/boot.cmd.in ${WORKDIR}/${UBOOT_ENV_BINARY}
-- 
2.47.0

**Comment by leon-anavi** [comment]
Hi @hmdevelopers,

Thank you for reporting this issue with meta-rauc-sunxi and providing a solution. Could you please clarify for which machine did you experience it?

Best regards,
Leon

**Comment by leon-anavi** [comment]
> sure thing: I am trying to get it working on orange-pi-zero2.
> 
> I keep you posted in case I succeed.

I have recently tested meta-rauc-sunxi on a couple of other Orange Pi boards:

* [Orange Pi Zero](http://www.orangepi.org/html/hardWare/computerAndMicrocontrollers/details/Orange-Pi-Zero.html)
* [Orange Pi One](http://www.orangepi.org/html/hardWare/computerAndMicrocontrollers/details/Orange-Pi-One.html)

Some tweaks will be required for orange-pi-zero2 but it should be similar to these other two Orange Pi boards.

For testing my `local.conf` for meta-sunxi included:

```
WKS_FILE = "sunxi-dual-image.wks.in"
WKS_FILES = "sunxi-dual-image.wks.in"
IMAGE_FSTYPES:append = " ext4"

DISTRO_FEATURES:append = " rauc"

INIT_MANAGER = "systemd"

IMAGE_INSTALL:append = " rauc-grow-data-part"
```

**Comment by hmdevelopers** [comment]
I did the build successfully, but it gets stuck on boot failing to load kernel.
Can you help me with this?



U-Boot SPL 2024.01-g (Jan 08 2024 - 15:37:48 +0000)
DRAM: 1024 MiB
Trying to boot from MMC1
NOTICE:  BL31: v2.10.4(release):lts-v2.10.4-dirty
NOTICE:  BL31: Built : 16:23:33, Apr 26 2024
NOTICE:  BL31: Detected Allwinner H616 SoC (1823)
NOTICE:  BL31: Found U-Boot DTB at 0x4a0b2a20, model: OrangePi Zero2


U-Boot 2024.01-g (Jan 08 2024 - 15:37:48 +0000) Allwinner Technology

CPU:   Allwinner H616 (SUN50I)
Model: OrangePi Zero2
DRAM:  1 GiB
Core:  54 devices, 22 uclasses, devicetree: separate
WDT:   Not starting watchdog@30090a0
MMC:   mmc@4020000: 0
Loading Environment from FAT... Unable to read "uboot.env" from mmc0:1...
In:    serial@5000000
Out:   serial@5000000
Err:   serial@5000000
Allwinner mUSB OTG (Peripheral)
Net:   eth0: ethernet@5020000using musb-hdrc, OUT ep1out IN ep1in STATUS ep2in
MAC de:ad:be:ef:00:01
HOST MAC de:ad:be:ef:00:00
RNDIS ready
, eth1: usb_ether
starting USB...
Bus usb@5200000: USB EHCI 1.00
Bus usb@5200400: USB OHCI 1.0
scanning bus usb@5200000 for devices... 1 USB Device(s) found
scanning bus usb@5200400 for devices... 1 USB Device(s) found
       scanning usb for storage devices... 0 Storage Device(s) found
Hit any key to stop autoboot:  0
switch to partitions #0, OK
mmc0 is current device
Scanning mmc 0:1...
Found U-Boot script /boot.scr
1746 bytes read in 1 ms (1.7 MiB/s)
## Executing script at 4fc00000
Found valid RAUC slot A
**Failed to load '@@KERNEL_IMAGETYPE@@'**
Saving Environment to FAT... OK
15356 bytes read in 3 ms (4.9 MiB/s)
Failed to load 'zImage'
Failed to load 'boot/zImage'
Failed to load 'uImage'
Failed to load 'boot/uImage'
Unknown command 'bootz' - try 'help'
Wrong Image Format for bootm command
ERROR: can't get kernel image!
SCRIPT FAILED: continuing...
15356 bytes read in 3 ms (4.9 MiB/s)
No EFI system partition
No EFI system partition
Failed to persist EFI variables
BootOrder not defined
EFI boot manager: Cannot load any image

Device 0: unknown device
BOOTP broadcast 1
DHCP client bound to address 192.168.16.96 (3 ms)
*** ERROR: `serverip' not set
Cannot autoload with TFTPGET
BOOTP broadcast 1
DHCP client bound to address 192.168.16.96 (4 ms)
*** ERROR: `serverip' not set
Cannot autoload with TFTPGET

**Comment by leon-anavi** [comment]
Looks like an issue with the generation of  `boot.scr` from `boot.cmd.in` for this board: https://github.com/rauc/meta-rauc-community/blob/b89bdf3469c5c1b83ee3395547151beb1884102b/meta-rauc-sunxi/recipes-bsp/u-boot/files/boot.cmd.in#L44

**Comment by hmdevelopers** [comment]
Thanks for pointing it out!

**Comment by hmdevelopers** [comment]
Hi @leon-anavi I have checked, and the recipes are not substituting @@KERNEL_IMAGETYPE@@ string with the KERNEL_IMAGETYPE set in the main conf file. Any idea of what I could check to fix it? By know I hardcoded and had the board boot properly.

**Comment by leon-anavi** [comment]
> Hi @leon-anavi I have checked, and the recipes are not substituting @@KERNEL_IMAGETYPE@@ string with the KERNEL_IMAGETYPE set in the main conf file. Any idea of what I could check to fix it? By know I hardcoded and had the board boot properly.

`boot.cmd.in` and the variable substation in it has to be adjusted for the specific boot sequence of the board on which you are integrating RAUC.
