### ISSUE TITLE
Home partition not mounted after update

### ISSUE THREAD

**Issue by alex88** [rauc/meta-rauc-community#15]
I've mentioned this in the irc channel because it was happening with my custom image and I gave a try using this layer on a brand new project as in https://www.konsulko.com/getting-started-with-rauc-on-raspberry-pi-2/ to understand if my custom image was the issue issue or also on the default one.

It seems that even in a default configuration, the /home extra partition isn't mounted after a rauc update.

Just to give a quick example:
 - build image as usual
 - flash image to rpi
 - boot and see that /home is in /etc/fstab (probably generated by https://github.com/leon-anavi/meta-rauc-community/blob/master/meta-rauc-raspberrypi/wic/sdimage-dual-raspberrypi.wks.in), /boot is also duplicated because of wic appending to the custom fstab file which already contains the boot partition
 - create bundle with bitbake update-bundle
 - download and  `rauc install` the bundle on the other partition
 - reboot
 - after reboot on the other slot /home isn't mounted and /etc/fstab only contains https://github.com/leon-anavi/meta-rauc-community/blob/master/meta-rauc-raspberrypi/recipes-core/base-files/files/fstab so only /boot is mounted

So I think the two viable solutions are to either:
 - add /home to /etc/fstab manually
 - figure out why the wic generated fstab doesn't apply to rauc bundle
 - or?

**Comment by ejoerns** [comment]
@alex88 There is no need to figure out why the wic-generated fstab doesn' apply to rauc bundle as wic is not involved in the image that ends up in the bundle. wic uses the generated rootfs *partition image* and manipulates this when creating the *disk image*.
The RAUC bundle of course uses the *partition image* only.

So the proper solution for this is to place the mount into /etc/fstab via manipulation of base-files.bb or, if you have systemd, make sure you have a mount unit set up for home.

**Comment by alex88** [comment]
Got it thank you!
