### ISSUE TITLE
Merge with meta-rauc-demo-wip (and others)

### ISSUE THREAD

**Issue by ejoerns** [rauc/meta-rauc-community#23]
Hi @leon-anavi,

thank you for creating this community-driven board support layer for RAUC :+1: 

To be honest: This was on my wishlist for quite some time. That's also why, some time ago, I started creating a demo board-support layer that I wanted to share here public. But, due to limited spare time I have never made it to a state where its initial functionality met the expectations we had.

As your layer made it into the RAUC organization, I would not pick up work on this separate layer and instead try to contribute things that I expect to be an 'added value' into this layer.

For reference: My work is located at

https://github.com/ejoerns/meta-rauc-demo-wip

and (depending on the branch) targets raspberrypi3 and qemux86.

Possibly there are also other similar layers outside that we can merge in this layer.

I for example know of

https://github.com/romainreignier/meta-rauc-qemux86

Maybe there are even more.

Many thanks in advance for your effort and maintenance!

**Comment by leon-anavi** [comment]
Hi @ejoerns,

RAUC is an awesome open source project and I happy that my modest contributions are useful for the community. It will be great if we can have more examples and demos for various machine in one place.

Thanks,
Leon

**Comment by ejoerns** [comment]
What do you think, I would propose to add the layers we have at the moment to the official layerindex.
Or did you do that already and they are in the approval process? ;)

Regards, Enrico

**Comment by leon-anavi** [comment]
Hi @ejoerns,

I think it is a great idea! I haven't submitted it yet. I had this in mind but constantly postponing it because I have been overloaded with other tasks recently.

Please feel free to submit `meta-rauc-community` to the official layerindex if you like. It will be great to spread to word about the layer and help other people find it easier.

Thanks,
Leon

**Comment by ejoerns** [comment]
Sounds like a plan :sweat_smile: :+1: . I can submit you as Layer maintainer with the mail you use in commits I assume? :wink:

**Comment by leon-anavi** [comment]
Yes, absolutely!

**Comment by ejoerns** [comment]
My first trial balloon made it into the layerindex somehow: http://layers.openembedded.org/layerindex/branch/master/layer/meta-rauc-raspberrypi/
But this seems to be largely broken... got an error when submitting, got an error for indexing.. But somehow it is at least listed now and I guess I can submit the other layers accordingly.

**Comment by dev-0x7C6** [comment]
I have same problem with indexer for [meta-octoprint](http://layers.openembedded.org/layerindex/branch/master/layer/meta-octoprint/) and other layers, this might be related to new override syntax.

**Comment by ejoerns** [comment]
I'd say the machine that runs the indexing deserves a distro/python upgrade: http://layers.openembedded.org/layerindex/layerupdate/9179134/

If I remember correctly, then the layerindex maintenance was already a topic at one of the last OEDEMs or Yocto Summits. But I do not have the details ready.

**Comment by ejoerns** [comment]
Layerindex looks as if it is working again. At least the builds do not fail anymore:

http://layers.openembedded.org/layerindex/branch/master/layer/meta-rauc-raspberrypi/

I tried to submit also the qemu layer (and ran into a missing 'thanks' page again), hope it will make it into the index, too.
Feel free to submit the others, too :)

The issue here can be closed. I still have some RPI patches lying around from my old integration, but that does not need to be tracked here :smirk:
