### ISSUE TITLE
Nothing provides atf-sunxi

### ISSUE THREAD

**Issue by hmdevelopers** [rauc/meta-rauc-community#72]
Hi, I am trying to build yocto for Orange Pi Zero 2 (Allwinner H616) with rauc support, but I am getting this error:

ERROR: Nothing PROVIDES 'atf-sunxi' (but /home/andrea/Documents/Development/HN3.0/yocto/layers/poky/meta/recipes-bsp/u-boot/u-boot_2023.10.bb DEPENDS on or otherwise requires it)
ERROR: Required build target 'core-image-minimal' has no buildable providers.

I could not find the missing atf-sunxi layer.

Any hint about this?

Thanks in advance

**Comment by hmdevelopers** [comment]
Fixed by building kirkstone branch.

**Comment by leon-anavi** [comment]
@hmdevelopers thank you for using meta-rauc-community and reporting the fix.
