### ISSUE TITLE
Question: Is there already suppport for uefi boot of jetson orin based products?

### ISSUE THREAD

**Issue by lesc-hexagon** [rauc/meta-rauc-community#75]
I need no bbapend for the UEFI recipe only uboot. Is this because UEFI woks out of the box or because nobody did use that yet?

**Comment by serafin-hexagon** [comment]
Sorry wrong layer

**Comment by leon-anavi** [comment]
@serafin-hexagon I have personally integrated RAUC for `jetson-tx2-devkit` only. I expect other Jetson machines will need further integration to get RAUC working on them.

**Comment by leon-anavi** [comment]
@lesc-hexagon I hope the provided information was useful. As there have been no follow up comments for a month I will close the issue.
